In [3]:
import task_generation.taskset_generation as tg
import numpy as np
from itertools import chain, repeat

In [4]:
u = np.array(tg.generate_uunifastdiscard(10, .5, 100, 'test.csv'))
u

array([[2.30927901e-03, 5.80046756e-03, 1.01335789e-03, 2.74961595e-04,
        9.05593238e-03, 2.95816035e-03, 6.57666055e-05, 1.83038276e-02,
        1.76386135e-02, 9.17665714e-04, 2.17365476e-03, 2.14504566e-03,
        2.84880343e-03, 1.98205541e-03, 1.05769755e-03, 8.69045427e-03,
        3.46619606e-03, 7.43682599e-04, 2.89633623e-02, 3.36734411e-03,
        7.51279329e-03, 3.67804948e-03, 2.35248009e-04, 4.75501921e-04,
        9.00255116e-03, 4.84563841e-03, 6.74013786e-04, 7.20080600e-04,
        4.73045995e-03, 3.49838357e-03, 8.50390078e-03, 9.41060809e-03,
        9.89294654e-04, 3.31113409e-03, 1.24819095e-02, 1.14852431e-03,
        6.91332048e-04, 6.11946085e-03, 2.66064704e-03, 2.05730343e-02,
        3.26219889e-03, 5.43430087e-04, 5.08864269e-04, 3.56898005e-03,
        4.95421654e-04, 5.40457729e-03, 5.01150645e-03, 6.94453548e-03,
        5.79315752e-03, 6.58784775e-04, 9.95862859e-03, 1.42135666e-03,
        1.24973145e-02, 8.58859701e-04, 2.60773537e-04, 3.539387

In [5]:
available_periods = list(range(1, 11))
p = np.array(tg.generate_random_periods_discrete(100, 10, available_periods))
p

array([[ 6,  6,  6,  7,  1,  6,  7,  5,  1,  3,  6,  6,  5,  5,  4,  8,
         3,  4,  2,  6,  4,  2,  1,  1,  7,  6,  6,  6, 10,  3,  8,  2,
         5,  5,  4,  7, 10,  6,  3,  5,  4,  2,  5,  9,  5,  9,  3,  7,
         9,  2,  4,  1,  9,  8,  5,  5,  3,  1,  7,  8,  8,  7,  5,  7,
         5,  8,  2,  3,  9,  9,  8,  4,  6,  9,  4,  2,  8,  8,  9,  6,
         4, 10,  7,  9, 10,  1,  3,  5,  9,  4,  5,  9,  8,  7,  7,  5,
         1,  6, 10,  5],
       [ 1,  8,  4,  9,  4,  5,  6,  3,  2,  6,  5,  2,  1, 10,  5,  2,
         7,  7,  8, 10,  6,  2,  7,  9,  2, 10,  7,  4,  4,  5,  4,  4,
         1,  4,  9,  1, 10, 10,  8, 10,  6,  1,  2,  8,  7,  6,  9,  9,
         6,  1,  7, 10,  1,  5,  1,  4,  6,  5, 10,  7,  7, 10,  1,  5,
         3,  8, 10,  1,  7,  4,  3,  3,  5,  9,  1,  5,  7,  3,  1,  5,
         9,  8,  3,  2,  2,  8, 10,  2,  4,  4,  1,  2,  3,  3,  2,  1,
         7,  6,  3,  6],
       [ 1,  7,  1,  5,  2,  5,  9,  2,  1,  6,  5, 10,  8,  5,  9,  5,
         2,  1

In [6]:
tset = np.array(tg.generate_tasksets(u, p, 'tset.csv'), dtype=[('cost', 'float64'), ('period', 'int32')])
tset.shape

(10, 100)

In [7]:
# get the hyper period of the task set
hp = np.lcm.reduce(tset['period'], axis=1)
hp

array([2520, 2520, 2520, 2520, 2520, 2520, 2520, 2520, 2520, 2520],
      dtype=int32)

In [8]:
# get release times, costs and deadlines for each taskset based on period and cost for a given hyper period
tasks = [
    list(chain.from_iterable([
        zip(
            list(range(0, hp[i_tset], tset['period'][i_tset, i_task])),
            list(range(tset['period'][i_tset, i_task], hp[i_tset] + 1, tset['period'][i_tset, i_task])),
            list(repeat(tset['cost'][i_tset, i_task], hp[i_tset] // tset['period'][i_tset, i_task]))
        ) for i_task in range(len(tset[i_tset]))
    ]))
    for i_tset in range(len(tset))
]