In [73]:
import task_generation.taskset_generation as tg
import numpy as np
from itertools import chain, repeat

In [74]:
u = np.array(tg.generate_uunifastdiscard(10, .5, 100, 'test.csv'))
u

array([[1.17237156e-02, 1.88037827e-03, 8.85510496e-03, 6.83044486e-03,
        9.01711138e-04, 3.82073262e-03, 7.67936252e-03, 1.29956121e-03,
        1.99040808e-03, 1.04218818e-03, 1.77578518e-03, 3.98082447e-03,
        1.16803694e-03, 1.04520371e-03, 3.38537151e-03, 1.76384124e-03,
        3.70471419e-03, 2.49818630e-03, 8.11620375e-03, 1.78265331e-03,
        1.46985345e-03, 1.95867695e-03, 1.31044134e-04, 8.31870310e-03,
        6.98531068e-03, 7.79748756e-03, 2.68709977e-03, 8.86997187e-03,
        1.04934094e-02, 2.63367509e-02, 1.96399825e-03, 3.63923699e-03,
        3.34793460e-03, 2.74044879e-02, 4.92400826e-03, 1.27526009e-02,
        4.12567018e-03, 5.50805283e-03, 1.92346124e-03, 5.31171558e-03,
        4.42908528e-03, 2.30976230e-03, 5.19286889e-04, 1.85296331e-03,
        4.07549397e-03, 9.29973685e-03, 7.57108936e-03, 1.81659781e-03,
        1.16409875e-02, 1.94437619e-03, 1.08864889e-02, 3.67205964e-03,
        1.24921264e-03, 6.61118089e-04, 8.78250887e-03, 3.230673

In [75]:
available_periods = list(range(1, 11))
p = np.array(tg.generate_random_periods_discrete(100, 10, available_periods))
p

array([[ 2,  1,  5,  7,  8,  4,  5,  1, 10,  6,  9,  5,  4,  8,  3,  3,
         4,  7,  3,  6, 10,  4,  9,  7,  9,  6,  4,  5, 10,  9,  4,  4,
         7,  1,  5,  1,  8,  6,  5, 10,  5,  3,  5,  1,  4,  9,  6,  2,
         4,  9,  6,  1,  8,  8,  6,  1,  2,  8,  5,  4,  9,  5,  5,  2,
         4,  2, 10,  2,  1,  4,  6,  5,  8,  8, 10,  2,  6,  6,  2,  4,
         1, 10,  3,  5,  3,  3,  8,  4,  8,  5,  6,  7,  6,  8,  7,  6,
         9,  4, 10,  7],
       [ 8,  2,  7,  3, 10,  2,  3, 10,  6,  4,  3, 10,  7,  4,  7,  7,
         3,  5,  4,  2,  4,  6,  1,  4,  8,  4,  2,  5,  9,  3,  3,  4,
         3, 10, 10,  9,  8,  9,  8,  5,  3,  2,  1,  2,  4,  3, 10,  5,
         6, 10,  6,  3,  6,  6,  3,  3,  7,  9,  9,  6,  1,  8,  5, 10,
         2,  5, 10,  9,  9,  9,  7,  5,  1,  7,  6,  8,  9,  4,  3,  9,
         8,  4,  2,  3,  2,  4,  4,  7,  8,  7,  9,  8, 10,  5,  3,  5,
         3,  7,  5,  9],
       [ 5,  2, 10,  8,  4,  4,  1,  1,  7,  5,  3,  1,  6,  8,  1,  2,
         2,  2

In [76]:
tset = np.array(tg.generate_tasksets(u, p, 'tset.csv'), dtype=[('cost', 'float64'), ('period', 'int32')])
tset.shape

(10, 100)

In [77]:
# get the hyper period of the task set
hp = np.lcm.reduce(tset['period'], axis=1)
hp

array([2520, 2520, 2520, 2520, 2520, 2520, 2520, 2520, 2520, 2520],
      dtype=int32)

In [78]:
# get release times, costs and deadlines for each taskset based on period and cost for a given hyper period
tasks = [
    list(chain.from_iterable([
        zip(
            list(range(0, hp[i_tset], tset['period'][i_tset, i_task])),
            list(range(tset['period'][i_tset, i_task], hp[i_tset] + 1, tset['period'][i_tset, i_task])),
            list(repeat(tset['cost'][i_tset, i_task], hp[i_tset] // tset['period'][i_tset, i_task]))
        ) for i_task in range(len(tset[i_tset]))
    ]))
    for i_tset in range(len(tset))
]

In [80]:
for i, taskset in enumerate(tasks):
    print(i, len(taskset))

0 70847
1 63135
2 78940
3 69243
4 65905
5 73191
6 77257
7 67538
8 82408
9 73256
